#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

$HOME/SALOME-9.14.0/salome -t create_baffles.py

mkdir -p constant/triSurface

cp baffles.stl constant/triSurface

restore0Dir

touch case.foam

runApplication blockMesh

runApplication snappyHexMesh -overwrite

runApplication extrudeMesh

runApplication createBaffles -overwrite

runApplication $(getApplication)